service: ebot7-sample-event-handlers

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  # e-bot7 Applications work with any framework and cloud provider
  # These examples use Serverless, Node, and AWS Lambdas
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  apiGateway:
    shouldStartNameWithService: true
  stage: ${opt:stage, 'dev'}
  profile: ${opt:profile, 'prod'}
  region: eu-central-1
  accountId: 060817847094
  endpointType: REGIONAL
  # This sample application is using AWS Secrets Manager to store its access token.
  # You can use the secure storage mechanism of your choice.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource:
        - arn:aws:secretsmanager:eu-central-1:${self:provider.accountId}:secret:${self:provider.stage}/SAMPLE_APPLICATION/CREDENTIALS*
functions:
  # This sample event handler receives an event when conversations are archived.
  # It fetches a list of messages from the conversation and prints them
  createTranscript:
    handler: handler.createTranscript
    events:
      - http:
          method: post
          path: transcript
    environment:
      token: ${self:provider.stage}/SAMPLE_APPLICATION/CREDENTIALS
